# Generated by Django 5.1.3 on 2024-11-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0002_source_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userincome",
            options={"ordering": ["-date"]},
        ),
    ]
